var domains = {
    "ffmsd01" : {id: "ffmsd01",short:"d01",name:"Münster Mitte-Süd"},
    "ffmsd02" : {id: "ffmsd02",short:"d02",name:"Münster Ost"},
    "ffmsd03" : {id: "ffmsd03",short:"d03",name:"Münster Nord"},
    "ffmsd04" : {id: "ffmsd04",short:"d04",name:"Münster West"},
    "ffmsd05" : {id: "ffmsd05",short:"d05",name:"Münster Süd"},
    "ffmsd07" : {id: "ffmsd07",short:"d07",name:"Telgte"},
    "ffmsd08" : {id: "ffmsd08",short:"d08",name:"Gescher"},
    "ffmsd09" : {id: "ffmsd09",short:"d09",name:"Stadtlohn"},
    "ffmsd10" : {id: "ffmsd10",short:"d10",name:"Borken Nord"},
    "ffmsd11" : {id: "ffmsd11",short:"d11",name:"Bocholt"},
    "ffmsd12" : {id: "ffmsd12",short:"d12",name:"Dülmen (ohne Rorup)"},
    "ffmsd13" : {id: "ffmsd13",short:"d13",name:"Rorup"},
    "ffmsd14" : {id: "ffmsd14",short:"d14",name:"Dingden"},
    "ffmsd15" : {id: "ffmsd15",short:"d15",name:"Heek"},
    "ffmsd16" : {id: "ffmsd16",short:"d16",name:"Münster Promenade"},
    "ffmsd17" : {id: "ffmsd17",short:"d17",name:"Emsdetten"},
    "ffmsd18" : {id: "ffmsd18",short:"d18",name:"Greven"},
    "ffmsd19" : {id: "ffmsd19",short:"d19",name:"Neuenkirchen"},
    "ffmsd20" : {id: "ffmsd20",short:"d20",name:"Ochtrup"},
    "ffmsd21" : {id: "ffmsd21",short:"d21",name:"Rheine"},
    "ffmsd22" : {id: "ffmsd22",short:"d22",name:"Steinfurt"},
    "ffmsd23" : {id: "ffmsd23",short:"d23",name:"Metelen"},
    "ffmsd24" : {id: "ffmsd24",short:"d24",name:"Wettringen"},
    "ffmsd26" : {id: "ffmsd26",short:"d26",name:"Borken Zentrum"},
    "ffmsd27" : {id: "ffmsd27",short:"d27",name:"Selm"},
    "ffmsd28" : {id: "ffmsd28",short:"d28",name:"Horstmar"},
    "ffmsd29" : {id: "ffmsd29",short:"d29",name:"Laer"},
    "ffmsd30" : {id: "ffmsd30",short:"d30",name:"Nordwalde"},
    "ffmsd31" : {id: "ffmsd31",short:"d31",name:"Altenberge"},
    "ffmsd32" : {id: "ffmsd32",short:"d32",name:"Ahlen"},
    "ffmsd33" : {id: "ffmsd33",short:"d33",name:"Beckum"},
    "ffmsd34" : {id: "ffmsd34",short:"d34",name:"Beelen"},
    "ffmsd35" : {id: "ffmsd35",short:"d35",name:"Drensteinfurt"},
    "ffmsd36" : {id: "ffmsd36",short:"d36",name:"Ennigerloh"},
    "ffmsd37" : {id: "ffmsd37",short:"d37",name:"Everswinkel"},
    "ffmsd38" : {id: "ffmsd38",short:"d38",name:"Oelde"},
    "ffmsd39" : {id: "ffmsd39",short:"d39",name:"Ostbevern"},
    "ffmsd40" : {id: "ffmsd40",short:"d40",name:"Sassenberg"},
    "ffmsd41" : {id: "ffmsd41",short:"d41",name:"Sendenhorst"},
    "ffmsd42" : {id: "ffmsd42",short:"d42",name:"Wadersloh"},
    "ffmsd43" : {id: "ffmsd43",short:"d43",name:"Warendorf"},
    "ffmsd44" : {id: "ffmsd44",short:"d44",name:"Ascheberg"},
    "ffmsd45" : {id: "ffmsd45",short:"d45",name:"Billerbeck"},
    "ffmsd46" : {id: "ffmsd46",short:"d46",name:"Coesfeld"},
    "ffmsd47" : {id: "ffmsd47",short:"d47",name:"Havixbeck"},
    "ffmsd48" : {id: "ffmsd48",short:"d48",name:"Lüdinghausen"},
    "ffmsd49" : {id: "ffmsd49",short:"d49",name:"Nordkirchen"},
    "ffmsd50" : {id: "ffmsd50",short:"d50",name:"Nottuln"},
    "ffmsd51" : {id: "ffmsd51",short:"d51",name:"Olfen"},
    "ffmsd52" : {id: "ffmsd52",short:"d52",name:"Rosendahl"},
    "ffmsd53" : {id: "ffmsd53",short:"d53",name:"Senden"},
    "ffmsd54" : {id: "ffmsd54",short:"d54",name:"Ahaus"},
    "ffmsd55" : {id: "ffmsd55",short:"d55",name:"Heiden"},
    "ffmsd56" : {id: "ffmsd56",short:"d56",name:"Isselburg"},
    "ffmsd57" : {id: "ffmsd57",short:"d57",name:"Legden"},
    "ffmsd58" : {id: "ffmsd58",short:"d58",name:"Reken"},
    "ffmsd59" : {id: "ffmsd59",short:"d59",name:"Rhede"},
    "ffmsd60" : {id: "ffmsd60",short:"d60",name:"Schöppingen"},
    "ffmsd61" : {id: "ffmsd61",short:"d61",name:"Südlohn"},
    "ffmsd62" : {id: "ffmsd62",short:"d62",name:"Velen"},
    "ffmsd63" : {id: "ffmsd63",short:"d63",name:"Vreden"},
    "ffmsd64" : {id: "ffmsd64",short:"d64",name:"Borken Süd"},
    "ffmsd66" : {id: "ffmsd66",short:"d66",name:"Bottrop"},
    "ffmsd67" : {id: "ffmsd67",short:"d67",name:"Dorsten"},
    "ffmsd68" : {id: "ffmsd68",short:"d68",name:"Gelsenkirchen"},
    "ffmsd69" : {id: "ffmsd69",short:"d69",name:"Gladbeck"},
    "ffmsd70" : {id: "ffmsd70",short:"d70",name:"Haltern am See"},
    "ffmsd71" : {id: "ffmsd71",short:"d71",name:"Herten"},
    "ffmsd72" : {id: "ffmsd72",short:"d72",name:"Marl"},
    "ffmsd73" : {id: "ffmsd73",short:"d73",name:"Raesfeld"},
    "ffmsd74" : {id: "ffmsd74",short:"d74",name:"Recklinghausen"},
    "ffmsd75" : {id: "ffmsd75",short:"d75",name:"Gronau"},
    "ffmsd76" : {id: "ffmsd76",short:"d76",name:"Herne"},
    "ffmsd77" : {id: "ffmsd77",short:"d77",name:"Hamm"},
    "ffmsd78" : {id: "ffmsd78",short:"d78",name:"Heppenheim"},
    "ffmsd79" : {id: "ffmsd79",short:"d79",name:"Heppenheim Umgebung"},
    "ffmsd80" : {id: "ffmsd80",short:"d80",name:"Hörstel"},
    "ffmsd81" : {id: "ffmsd81",short:"d81",name:"Ibbenbüren"},
    "ffmsd82" : {id: "ffmsd82",short:"d82",name:"Ladbergen"},
    "ffmsd83" : {id: "ffmsd83",short:"d83",name:"Lengerich"},
    "ffmsd84" : {id: "ffmsd84",short:"d84",name:"Lienen"},
    "ffmsd85" : {id: "ffmsd85",short:"d85",name:"Saerbeck"},
    "ffmsd86" : {id: "ffmsd86",short:"d86",name:"Tecklenburg"},
    "ffmsd87" : {id: "ffmsd87",short:"d87",name:"Bad Iburg"},
    "ffmsd88" : {id: "ffmsd88",short:"d88",name:"Georgsmarienhütte"},
    "ffmsd89" : {id: "ffmsd89",short:"d89",name:"Hagen am Teutoburger Wald"},
    "ffmsd90" : {id: "ffmsd90",short:"d90",name:"Datteln"},
    "ffmsd91" : {id: "ffmsd91",short:"d91",name:"Waltrop"},
    "ffmsd92" : {id: "ffmsd92",short:"d92",name:"Oer-Erkenschwick"},
    "ffmsd93" : {id: "ffmsd93",short:"d93",name:"Castrop-Rauxel"}
}
