var domains = {
    "domaene01" : {id: "domaene01",short:"d01",name:"Münster Mitte-Süd"},
    "domaene02" : {id: "domaene02",short:"d02",name:"Münster Ost"},
    "domaene03" : {id: "domaene03",short:"d03",name:"Münster Nord"},
    "domaene04" : {id: "domaene04",short:"d04",name:"Münster West"},
    "domaene05" : {id: "domaene05",short:"d05",name:"Münster Süd"},
    "domaene07" : {id: "domaene07",short:"d07",name:"Telgte"},
    "domaene08" : {id: "domaene08",short:"d08",name:"Gescher"},
    "domaene09" : {id: "domaene09",short:"d09",name:"Stadtlohn"},
    "domaene10" : {id: "domaene10",short:"d10",name:"Borken Nord"},
    "domaene11" : {id: "domaene11",short:"d11",name:"Bocholt"},
    "domaene12" : {id: "domaene12",short:"d12",name:"Dülmen (ohne Rorup)"},
    "domaene13" : {id: "domaene13",short:"d13",name:"Rorup"},
    "domaene14" : {id: "domaene14",short:"d14",name:"Dingden"},
    "domaene15" : {id: "domaene15",short:"d15",name:"Heek"},
    "domaene16" : {id: "domaene16",short:"d16",name:"Münster Promenade"},
    "domaene17" : {id: "domaene17",short:"d17",name:"Emsdetten"},
    "domaene18" : {id: "domaene18",short:"d18",name:"Greven"},
    "domaene19" : {id: "domaene19",short:"d19",name:"Neuenkirchen"},
    "domaene20" : {id: "domaene20",short:"d20",name:"Ochtrup"},
    "domaene21" : {id: "domaene21",short:"d21",name:"Rheine"},
    "domaene22" : {id: "domaene22",short:"d22",name:"Steinfurt"},
    "domaene23" : {id: "domaene23",short:"d23",name:"Metelen"},
    "domaene24" : {id: "domaene24",short:"d24",name:"Wettringen"},
    "domaene26" : {id: "domaene26",short:"d26",name:"Borken Zentrum"},
    "domaene27" : {id: "domaene27",short:"d27",name:"Selm"},
    "domaene28" : {id: "domaene28",short:"d28",name:"Horstmar"},
    "domaene29" : {id: "domaene29",short:"d29",name:"Laer"},
    "domaene30" : {id: "domaene30",short:"d30",name:"Nordwalde"},
    "domaene31" : {id: "domaene31",short:"d31",name:"Altenberge"},
    "domaene32" : {id: "domaene32",short:"d32",name:"Ahlen"},
    "domaene33" : {id: "domaene33",short:"d33",name:"Beckum"},
    "domaene34" : {id: "domaene34",short:"d34",name:"Beelen"},
    "domaene35" : {id: "domaene35",short:"d35",name:"Drensteinfurt"},
    "domaene36" : {id: "domaene36",short:"d36",name:"Ennigerloh"},
    "domaene37" : {id: "domaene37",short:"d37",name:"Everswinkel"},
    "domaene38" : {id: "domaene38",short:"d38",name:"Oelde"},
    "domaene39" : {id: "domaene39",short:"d39",name:"Ostbevern"},
    "domaene40" : {id: "domaene40",short:"d40",name:"Sassenberg"},
    "domaene41" : {id: "domaene41",short:"d41",name:"Sendenhorst"},
    "domaene42" : {id: "domaene42",short:"d42",name:"Wadersloh"},
    "domaene43" : {id: "domaene43",short:"d43",name:"Warendorf"},
    "domaene44" : {id: "domaene44",short:"d44",name:"Ascheberg"},
    "domaene45" : {id: "domaene45",short:"d45",name:"Billerbeck"},
    "domaene46" : {id: "domaene46",short:"d46",name:"Coesfeld"},
    "domaene47" : {id: "domaene47",short:"d47",name:"Havixbeck"},
    "domaene48" : {id: "domaene48",short:"d48",name:"Lüdinghausen"},
    "domaene49" : {id: "domaene49",short:"d49",name:"Nordkirchen"},
    "domaene50" : {id: "domaene50",short:"d50",name:"Nottuln"},
    "domaene51" : {id: "domaene51",short:"d51",name:"Olfen"},
    "domaene52" : {id: "domaene52",short:"d52",name:"Rosendahl"},
    "domaene53" : {id: "domaene53",short:"d53",name:"Senden"},
    "domaene54" : {id: "domaene54",short:"d54",name:"Ahaus"},
    "domaene55" : {id: "domaene55",short:"d55",name:"Heiden"},
    "domaene56" : {id: "domaene56",short:"d56",name:"Isselburg"},
    "domaene57" : {id: "domaene57",short:"d57",name:"Legden"},
    "domaene58" : {id: "domaene58",short:"d58",name:"Reken"},
    "domaene59" : {id: "domaene59",short:"d59",name:"Rhede"},
    "domaene60" : {id: "domaene60",short:"d60",name:"Schöppingen"},
    "domaene61" : {id: "domaene61",short:"d61",name:"Südlohn"},
    "domaene62" : {id: "domaene62",short:"d62",name:"Velen"},
    "domaene63" : {id: "domaene63",short:"d63",name:"Vreden"},
    "domaene64" : {id: "domaene64",short:"d64",name:"Borken Süd"},
    "domaene66" : {id: "domaene66",short:"d66",name:"Bottrop"},
    "domaene67" : {id: "domaene67",short:"d67",name:"Dorsten"},
    "domaene68" : {id: "domaene68",short:"d68",name:"Gelsenkirchen"},
    "domaene69" : {id: "domaene69",short:"d69",name:"Gladbeck"},
    "domaene70" : {id: "domaene70",short:"d70",name:"Haltern am See"},
    "domaene71" : {id: "domaene71",short:"d71",name:"Herten"},
    "domaene72" : {id: "domaene72",short:"d72",name:"Marl"},
    "domaene73" : {id: "domaene73",short:"d73",name:"Raesfeld"},
    "domaene74" : {id: "domaene74",short:"d74",name:"Recklinghausen"},
    "domaene75" : {id: "domaene75",short:"d75",name:"Gronau"},
    "domaene76" : {id: "domaene76",short:"d76",name:"Herne"},
    "domaene77" : {id: "domaene77",short:"d77",name:"Hamm"},
    "domaene78" : {id: "domaene78",short:"d78",name:"Heppenheim"},
    "domaene79" : {id: "domaene79",short:"d79",name:"Heppenheim Umgebung"},
    "domaene80" : {id: "domaene80",short:"d80",name:"Hörstel"},
    "domaene81" : {id: "domaene81",short:"d81",name:"Ibbenbüren"},
    "domaene82" : {id: "domaene82",short:"d82",name:"Ladbergen"},
    "domaene83" : {id: "domaene83",short:"d83",name:"Lengerich"},
    "domaene84" : {id: "domaene84",short:"d84",name:"Lienen"},
    "domaene85" : {id: "domaene85",short:"d85",name:"Saerbeck"},
    "domaene86" : {id: "domaene86",short:"d86",name:"Tecklenburg"},
    "domaene87" : {id: "domaene87",short:"d87",name:"Bad Iburg"},
    "domaene88" : {id: "domaene88",short:"d88",name:"Georgsmarienhütte"},
    "domaene89" : {id: "domaene89",short:"d89",name:"Hagen am Teutoburger Wald"},
    "domaene90" : {id: "domaene90",short:"d90",name:"Datteln"},
    "domaene91" : {id: "domaene91",short:"d91",name:"Waltrop"},
    "domaene92" : {id: "domaene92",short:"d92",name:"Oer-Erkenschwick"},
    "domaene93" : {id: "domaene93",short:"d93",name:"Castrop-Rauxel"}
}